version: 2.1 # Use v2.1 to enable orb usage.

jobs:
  build:
    docker:
      - image: alpine:3.7
    parallelism: 4
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
