version: 2.1 
orbs:
  macos: circleci/macos@1.0.0

jobs:
  build:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 # indicate our selected version of Xcode
    
    parallelism: 1
    
    steps:
      - checkout
      - run: echo "Write-Host 'Hello, Macos"
